server:
  port: 9999
  tomcat:
    accesslog:
      enabled: true
endpoints:
  sensitive: false
spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:inventory
pet-store:
  oauth:
    tokenTimeout: 3600
#security:
#  user:
#    name: admin
#    password: admin
#    role: USER
#  oauth2:
#    client:
#      client-id: adminclient
#      client-secret: adminsecret
#      scope: read,write
#      auto-approve-scopes: '.*'