debug: true
endpoints:
  sensitive: false
server:
  port: 8091
  tomcat:
    accesslog:
      enabled: true
management:
  security: 
    enabled: false
spring:
#  h2:
#    console:
#      enabled: true
  datasource:
    url: jdbc:mysql://localhost:3306/pet
    username: root
    password: root
  jpa:
      hibernate:
        ddl-auto: update
#  rabbitmq:
#    host: localhost
#    port: 5672
#flyway:
#  clean-on-validation-error: true
#  check-location: true
#  locations: classpath:db/migration
#  baseline-on-migrate: true
jwt:
  secret: mySecret
  header: Authorization
  expiration: 604800
  route:
    authentication:
     path: auth
     refresh: refresh
security:
  ignored: /favicon.ico
  basic:
    enabled: false
---
#spring:
#  profiles: dev-postgres
#  datasource:
#    url: jdbc:postgresql://127.0.0.1:5432/product_service_dataservice
#    username: postgres
#    password: root
#    driver-class-name: org.postgresql.Driver

#server:
#  port: 8082
#---
spring:
  profiles: cloud
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5Dialect
    